version: '3.8'

networks:
  dev:
    driver: bridge 

services:
  movies-service:
    image: ${REGISTRY:-movies}/movies.api:${PLATFORM:-linux}-${TAG:-latest}
    depends_on:
      - "db"
    container_name: movies-service
    ports:
      - "5009:80"
    build:
      context: .
      dockerfile: Movies.API/Dockerfile
    environment:
      - ConnectionString=host=db;port=5431;database=movies_db;username=postgres;password=postgres;Pooling=true;
      - ASPNETCORE_ENVIRONMENT=Development
      - HostName=cache
      - PortNumber=6379
      - Password=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    networks:
      - dev

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5431:5432"
    restart: always
    volumes:
      - customer_data:/var/lib/postgresql/data/ 
    networks:
      - dev

  cache:
    image: redis:6.2-alpine
    container_name: cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
    networks:
      - dev

volumes:
  customer_data:
  cache:
